# Generated by Django 6.0.6 on 2026-06-14 07:58

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measured_at", models.DateTimeField(db_index=True)),
                ("value_m_nap", models.FloatField()),
                ("quality", models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Well",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bro_id", models.CharField(db_index=True, max_length=40, unique=True)),
                ("tube_number", models.PositiveSmallIntegerField(default=1)),
                ("nitg_code", models.CharField(blank=True, max_length=20)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("ground_level_m", models.FloatField(blank=True, null=True)),
                ("tube_top_m", models.FloatField(blank=True, null=True)),
                ("screen_top_m", models.FloatField(blank=True, null=True)),
                ("screen_bottom_m", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("pdok_updated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WellBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[("week", "Week"), ("month", "Month")],
                        default="week",
                        max_length=5,
                    ),
                ),
                ("period_index", models.PositiveSmallIntegerField()),
                ("p5", models.FloatField()),
                ("p10", models.FloatField()),
                ("p25", models.FloatField()),
                ("p50", models.FloatField()),
                ("p75", models.FloatField()),
                ("p90", models.FloatField()),
                ("p95", models.FloatField()),
                ("mean", models.FloatField()),
                ("std", models.FloatField()),
                ("sample_count", models.PositiveIntegerField()),
                ("baseline_start", models.DateField()),
                ("baseline_end", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="IngestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=40)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("wells_processed", models.PositiveIntegerField(default=0)),
                ("errors_json", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["kind", "started_at"],
                        name="api_ingestr_kind_cfa5d2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WellStatus",
            fields=[
                (
                    "well",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="status",
                        serialize=False,
                        to="api.well",
                    ),
                ),
                ("latest_value_m_nap", models.FloatField(blank=True, null=True)),
                ("latest_measured_at", models.DateTimeField(blank=True, null=True)),
                ("percentile", models.FloatField(blank=True, null=True)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("very_low", "Very low"),
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("very_high", "Very high"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("is_stale", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddIndex(
            model_name="well",
            index=models.Index(fields=["bro_id"], name="api_well_bro_id_9fe670_idx"),
        ),
        migrations.AddField(
            model_name="measurement",
            name="well",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measurements",
                to="api.well",
            ),
        ),
        migrations.AddField(
            model_name="wellbaseline",
            name="well",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baselines",
                to="api.well",
            ),
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(
                fields=["well", "measured_at"], name="api_measure_well_id_13086f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="measurement",
            constraint=models.UniqueConstraint(
                fields=("well", "measured_at"), name="unique_well_measured_at"
            ),
        ),
        migrations.AddIndex(
            model_name="wellbaseline",
            index=models.Index(
                fields=["well", "period_type", "period_index"],
                name="api_wellbas_well_id_9c6518_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="wellbaseline",
            constraint=models.UniqueConstraint(
                fields=("well", "period_type", "period_index"),
                name="unique_well_period",
            ),
        ),
    ]
