# Generated by Django 6.0.6 on 2026-06-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="well",
            name="gld_bro_id",
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
