# Generated by Django 6.0.6 on 2026-06-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_add_gld_bro_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="well",
            name="research_last_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
