# Generated by Django 6.0.6 on 2026-06-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_gld_link_checked_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wellstatus",
            name="well",
        ),
        migrations.RenameIndex(
            model_name="measurement",
            new_name="api_measure_well_id_89b3bf_idx",
            old_name="api_measur_well_id_measured_on_idx",
        ),
        migrations.DeleteModel(
            name="WellStatus",
        ),
    ]
