# Generated by Django 6.0.6 on 2026-08-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_wellstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "kvk_number",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("resolved_at", models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name="well",
            name="bro_object_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="well",
            name="bronhouder_kvk",
            field=models.CharField(blank=True, db_index=True, max_length=8),
        ),
        migrations.AddField(
            model_name="well",
            name="owner_kvk",
            field=models.CharField(blank=True, db_index=True, max_length=8),
        ),
    ]
