# Generated by Django 6.0.6 on 2026-08-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_well_ownership"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitoringNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bro_id", models.CharField(db_index=True, max_length=40, unique=True)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("monitoring_purpose", models.CharField(blank=True, max_length=80)),
                ("groundwater_aspect", models.CharField(blank=True, max_length=40)),
                ("delivery_context", models.CharField(blank=True, max_length=80)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("bro_object_url", models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="well",
            name="initial_function",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="well",
            name="number_of_monitoring_tubes",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="well",
            name="research_first_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="well",
            name="well_construction_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="well",
            name="monitoring_networks",
            field=models.ManyToManyField(
                blank=True, related_name="wells", to="api.monitoringnetwork"
            ),
        ),
    ]
