# Generated by Django 6.0.6 on 2026-08-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_well_metadata_and_networks"),
    ]

    operations = [
        migrations.AddField(
            model_name="well",
            name="measurement_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("yearly", "Yearly"),
                    ("irregular", "Irregular"),
                ],
                db_index=True,
                max_length=20,
                null=True,
            ),
        ),
    ]
