# Generated by Django 6.0.6 on 2026-08-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_well_measurement_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="well",
            name="first_measured_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="well",
            name="last_measured_on",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="well",
            name="measurement_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE api_well AS well
                SET
                    first_measured_on = stats.first_on,
                    last_measured_on = stats.last_on,
                    measurement_count = stats.n
                FROM (
                    SELECT
                        well_id,
                        MIN(measured_on) AS first_on,
                        MAX(measured_on) AS last_on,
                        COUNT(*)::integer AS n
                    FROM api_measurement
                    GROUP BY well_id
                ) AS stats
                WHERE well.id = stats.well_id;
            """,
            reverse_sql="""
                UPDATE api_well
                SET
                    first_measured_on = NULL,
                    last_measured_on = NULL,
                    measurement_count = 0;
            """,
        ),
    ]
